#!/usr/bin/env bash
conda install -y -q anaconda-client 
conda install -y -q panda
conda install -y -q wget workerpool parsel memory_profiler libuuid jpeg joblib basemap numpy scikit-image scikit-learn neon statsmodels matplotlib ujson gevent-websocket pymongo jmespath iopro pandas nltk
echo "-----> Libraries installed"
