#!/usr/bin/env bash

conda install -y anaconda-client 
conda install -y wget workerpool parsel memory_profiler libuuid jpeg joblib basemap numpy scikit-image scikit-learn neon statsmodels matplotlib ujson gevent-websocket pymongo jmespath iopro pandas nltk &

pgcontents init -l $DATABASE_URL --no-prompt

jupyter notebook \
	--no-browser --no-mathjax --ip=* --port $PORT \
	--config=jupyterconfig.py \
	notebooks

echo "---> PASE POR AQUI" 
