#!/usr/bin/env bash

pgcontents init -l $DATABASE_URL --no-prompt

chmod 555 load_libraries
./load_libraries &

jupyter notebook \
	--no-browser --no-mathjax --ip=* --port $PORT \
	--config=jupyterconfig.py \
	notebooks
